name: Cypress CI

on:
  pull_request:
    branches: [master]

jobs:
  cypress:
    name: 'Cypress Test'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v1

      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Set up Expo
        uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-cache: true

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Cache Cypress binary
        uses: actions/cache@v2
        with:
          path: ~/.cache/Cypress
          key: cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}
          restore-keys: |
            cypress-${{ runner.os }}-cypress-${{ hashFiles('**/package.json') }}

      - name: Install dependencies
        run: |
          npm ci
          npm run prestorybook

      - name: Run tests
        run: |
          npm run web:ci
          npm run e2e:web:run:ci
